### PR TITLE
feat: add ability for producer to produce using JSON body

### PR DESCRIPTION
**Pull request by maetolay**
## Pull Request Submission Checklist

Please confirm that you have done the following before requesting reviews:

- [x] I have confirmed that the PR type is appropriate for the change I am making according to
  the [Honest Pull Request and Commit Message Naming Conventions](https://www.notion.so/honestbank/Pull-Request-and-Commit-Message-Naming-Conventions-bd97f2cbb34c4c73b1ff3a3e384b850c).
- [x] I have typed an adequate description that explains **why** I am making this change.
- [x] I have installed and run standard pre-commit hooks that lints and validates my code.

### Description

* Add an ability for V2 to produce JSON body

- - -
This change is [Reviewable](https://reviewable.io/reviews/honestbank/kp/64)

### CODE REVIEW

**Review by dantodor — APPROVED** [review]

**Comment by cyberhck** [comment]
I'd like to approach this in a slightly different way. Do you mind using from this branch for now?

**Comment by maetolay** [comment]
> I'd like to approach this in a slightly different way. Do you mind using from this branch for now?

I can wait and let you take over the branch, we just need this to work before we could use this for confluent migration work

**Review by cyberhck — CHANGES_REQUESTED** [review]
consumer needs some work, while this is a really good idea, I wanted to make the consumer dumber. And give the ability for people to produce how they want. And remove the avro completely and only allow `Produce` method.

That way if they want to use schema registry, they can, if they don't want, they won't have to.
Or if there's a way to use schema registry with non avro formats like json, they might be able to. In theory that should be possible.

I'll dumb down the producer when I get a chance.

**Comment by cyberhck** [comment]
I got an untyped producer code ready which will be used by all typed producers. I will get back to that after our internal kafka migration is concluded.

**Comment by cyberhck** [comment]
untyped producer is now available. will revamp typed in the future.

**Pull request closed without merging**
